### ISSUE TITLE
Default/example values when a model definition is present

### ISSUE THREAD

**Issue by gietl** [APIDevTools/swagger-express-middleware#11]
We are currently implementing a new set of api's and using the swagger spec. Trying to find a quick way for FE devs to have data be mocked while the services are being built. I have found the auto mocking of default values works fine until there is a ref to a defined model. 

Ideally, we should be able to define everything, and utilize default or example (ideally example) so we can quickly use the mock middleware without the need to have "temporary" things in the yaml. It's entirely possible I missed something in the documentation. Still ramping up on the spec and these tools.

Also, I've never got "example" to work, only "default."

Thank you for taking a look at my questions.

For default this works:

```
/pets/{petName}:
    parameters:
      - $ref: "#/parameters/petName"

    get:
      description: Returns a pet by name
      operationId: findPetByName
      responses:
        default:
          description: Returns the pet data
          schema:
            default:
              name: "Fido"
              type: "dog"
              age: 9
          headers:
            last-modified:
              type: string
              description: The date/time that the pet was last modified
```

but this does not:

```
/pets/{petName}:
    parameters:
      - $ref: "#/parameters/petName"

    get:
      description: Returns a pet by name
      operationId: findPetByName
      responses:
        default:
          description: Returns the pet data
          schema:
            $ref: "#/definitions/pet"
            default:
              name: "Fido"
              type: "dog"
              age: 9
          headers:
            last-modified:
              type: string
              description: The date/time that the pet was last modified
```

**Comment by gietl** [comment]
I think I discovered my oversight, it appears I need to put the default or example data in the model definition when there is a ref to it. It appears to be working for me now.

**Comment by BigstickCarpet** [comment]
Ah, yes.  That's a [known bug in Swagger Parser](https://github.com/BigstickCarpet/swagger-parser/issues/14) (which Swagger Express Middleware uses under the hood).  It will be fixed in the next release.

**Comment by gietl** [comment]
Great, thanks for the info!
