### ISSUE TITLE
operationId not binding to function name

### ISSUE THREAD

**Issue by JonnyWaffles** [APIDevTools/swagger-express-middleware#123]
I read through the documentation and samples, but it is unclear as to how one binds operationId function names to functions. The samples don't contain any of the function names included in the example yaml operationId. 

index.js
```
const path = require('path');
const express = require('express');
const createMiddleware = require('swagger-express-middleware');

const app = express();

app.use(express.static('models'));



const swaggerFile = path.join(__dirname, 'swagger.yaml')

createMiddleware(swaggerFile, app, (err, middleware) => {
    app.use(
        middleware.metadata(),
        middleware.CORS(),
        middleware.files(),
        middleware.parseRequest(),
        middleware.validateRequest(),
        middleware.mock()
    );

    const server = app.listen(process.env.PORT || 9000)
    console.log('Listening on port %d', server.address().port)
})

function TestMethod(req, res, next) {
    console.log('TEST');
    res.json({message: req.swagger.params.message.value || 'Banana Phone.'});
}
```

swagger.yml
```
paths:

  /test:
    get:
      operationId: TestMethod
      responses:
        200:
          description: Yay

  /test/{message}:
    parameters:
      - name: message
        in: path
        type: string
        required: true
    get:
      operationId: TestMethod
      responses:
        200:
          description: Validated
          schema:
            type: object
```

I would expect TestMethod to be called but if I hit localhost:9000/api/test an empty page loads and TEST is never logged to console so I know TestMethod is never being called. Would you be so kind as to clarify how I bind the handler?

**Comment by JamesMessinger** [comment]
Swagger Express Middleware doesn't route by operationId.  It relies on Express's default path-based routing.   See [this example](https://apidevtools.org/swagger-express-middleware/docs/middleware/parseRequest.html#example) in the docs for a sample of adding an API path handler.
