### ISSUE TITLE
Issue with path params

### ISSUE THREAD

**Issue by Nomeasmo** [APIDevTools/swagger-express-middleware#127]
https://github.com/APIDevTools/swagger-express-middleware/blob/30336ec7a12a2d2aa4dfda297ce2be1b9160e378/lib/path-parser.js#L139

The `paramParser.parseParameter ` is not called with the schema but with the whole parameter object.

Correct version: 
```
req.pathParams[paramName] = paramParser.parseParameter(param, paramValue, param.schema);
```

BTW: would highly appreciate not to create an PR for this since you guys likely add unit tests as well and it is likely more easy for you ..... ;)

**Comment by JamesMessinger** [comment]
@Nomeasmo - Swagger Express Middleware currently supports Swagger 2.0, not OpenAPI 3.0, which is why the above code does not work.
