### ISSUE TITLE
Api Key seems not to follow standard

### ISSUE THREAD

**Issue by Nomeasmo** [APIDevTools/swagger-express-middleware#129]
According to some code inspections I need to modify the OpenAPI in order to let the middleware work properly for api keys. Instead of picking up the api key schema from `components.securitySchemes` it uses non standard `securityDefinitions`.

Refer to [API Key on swagger.io](https://swagger.io/docs/specification/authentication/api-keys/)

```
const prepareForValidation = (openapiDoc) => ({
  ...openapiDoc,
  basePath: '/api/v1',
  securityDefinitions: openapiDoc.components.securitySchemes
});
```

**Comment by JamesMessinger** [comment]
@Nomeasmo - `components` and `securitySchems` are OpenAPI 3.0 concepts.  They don't exist in Swagger 2.0, which is what Swagger Express Middleware currently supports.
