### ISSUE TITLE
Feature: add requestBody parser

### ISSUE THREAD

**Issue by Nomeasmo** [APIDevTools/swagger-express-middleware#130]
Would be nice to see a `requestBody` parser that also validates OpenAPI like this:

```
...
    "/user": {
      "put": {
        "summary": "Creates a user.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              }
            }
          }
        },
...
```

**Comment by JamesMessinger** [comment]
@Nomeasmo - `requestBody` is an OpenAPI 3.0 concepts  It doesn't exist in Swagger 2.0, which is what Swagger Express Middleware currently supports.

**Comment by airen29** [comment]
Hello since you are currently started to "add support" for `3.0.0` is it possible that you could include `requestBody` parser into it? Would be helpful. Thanks a lot :+1:

**Comment by JamesMessinger** [comment]
100% agreed.  That's a must-have for OpenAPI 3 support

**Comment by airen29** [comment]
Thanks for the quick answer @JamesMessinger , is there any promise where we can expect that? We as a team build a full OpenAPI 3 yaml files and now are hanging out there without `req.body` basicly :) 

Should we rewrite our files or convert them to `Swagger 2.0` for now? Thanks a lot James.

**Comment by JamesMessinger** [comment]
I can't make any promises about ETA, since it depends on how busy @rkrauskopf  and I are at work.  We try to devote at least 10 hours per week to working on these projects though.

**Comment by airen29** [comment]
Hello. Any new info about `middleware-parser` in OA3.0 ? :) Thanks
