### ISSUE TITLE
How to disable validate

### ISSUE THREAD

**Issue by lwf804** [APIDevTools/swagger-express-middleware#132]
I want to turn off validate. But cant find any way?

**Comment by lwf804** [comment]
So, have any way to show error by json format:
```
<h1>400 Error</h1><pre>The "taskInfo" body parameter is invalid ({"userId":"1","workId":1,"workTypeId":1}) 
JSON Schema validation error. 
Data path: "/userId" 
Schema path: "/properties/userId/type" 
Invalid type: string (expected integer)</pre>
```

Thanks!

**Comment by JamesMessinger** [comment]
Swagger Express Middleware throws errors in such a way that they can be handled by standard [Express.js error-handling middleware](https://expressjs.com/en/guide/error-handling.html).  You can do whatever you want in your middleware, such as formatting the error as JSON, HTML, XML, etc., or even ignoring the error altogether and continuing with the request.

**Comment by lwf804** [comment]
I found. Thanks you!
