### ISSUE TITLE
Breaking changes in v2?

### ISSUE THREAD

**Issue by bobby-brennan** [APIDevTools/swagger-express-middleware#137]
Hi there,

I'm updating [DataFire](https://github.com/DataFire/DataFire) to use `2.0.1`, and we have lots of downstream users. The tests pass without any changes, but I'm guessing there are some breaking changes given the major release. 

Anything I should be aware of here?

Thanks!

**Comment by rkrauskopf** [comment]
The only changes in v2 are dependency updates, but we bumped a major version simply out of caution since the dependencies were so outdated.

**Comment by bobby-brennan** [comment]
Thanks!
