### ISSUE TITLE
Is the support to openAPI 3.0 available now ?

### ISSUE THREAD

**Issue by nagarajanceg** [APIDevTools/swagger-express-middleware#142]
Looking for a middleware for openAPI 3.0 for schema validation and routing. I use this module previously for swagger 2.0 and it works perfect.

**Comment by JamesMessinger** [comment]
Not quite yet, but we're actively working on it in [the v3 branch](https://github.com/APIDevTools/swagger-express-middleware/tree/v3)

**Comment by JamesMessinger** [comment]
We are now publishing **alpha** releases to npm with some support for OpenAPI 3.0.  These alphas are based on [the v3 branch](https://github.com/APIDevTools/swagger-express-middleware/tree/v3).  See [the ReadMe](https://github.com/APIDevTools/swagger-express-middleware/tree/v3#readme) and [the changelog](https://github.com/APIDevTools/swagger-express-middleware/blob/v3/CHANGELOG.md) for more details.
