### ISSUE TITLE
metadata middleware is slow for big swagger file

### ISSUE THREAD

**Issue by dolguji** [APIDevTools/swagger-express-middleware#154]
We have noticed that metadata middleware takes over 20 ms to set a swagger path to request object and upon investigation this was due to the dynamic creation of RegEx instance per path. When swagger definition contains about 500 paths, it is taking over 20ms just to run regular expression test. I was able to reduce the runtime from 20ms to 1-2 ms by caching the regular expression instance (i.e. pre-populate regular expression instances). 

Also confirmed the `swagger-express-mw` performs much better for finding swagger path and this was because it caches the regular expression per path (using sway package).

I have a fix for this issue and will create a PR.

Thanks!

**Comment by JamesMessinger** [comment]
Fixed by #155
