### ISSUE TITLE
Automatic routing from swagger api doc

### ISSUE THREAD

**Issue by raulhsj** [APIDevTools/swagger-express-middleware#156]
Hi,
  I was wondering if the library offers any way to parse ``` x-swagger-router-controller ``` and ``` operationId ``` nodes to achieve automatic routing to the controller method when a path is hit.

**Comment by JamesMessinger** [comment]
This library doesn't provide any routing functionality.

**Comment by ezos86** [comment]
Happy it doesn't - I think documentation should be independent from the controller.
