### ISSUE TITLE
NPM audit issue

### ISSUE THREAD

**Issue by Nomeasmo** [APIDevTools/swagger-express-middleware#162]
This morning I had this with current 2.0.5 version:

│ High          │ Prototype Pollution Protection Bypass                        │
│ Package       │ qs                                                           │
│ Patched in    │ >=6.0.4 <6.1.0 || >=6.1.2 <6.2.0 || >=6.2.3 <6.3.0 ||        │
│               │ >=6.3.2                                                      │
│ Dependency of │ swagger-express-middleware                                   │
│ Path          │ swagger-express-middleware > multer > qs                     │
│ More info     │ https://npmjs.com/advisories/1469                            │
found 1 high severity vulnerability in 891034 scanned packages
  1 vulnerability requires manual review. See the full report for details.

Current version of multer does not seem to require qs anymore.

This is blocking our build process. A simple `npm audit fix` in this  case did not  help.

**Comment by dave-irvine** [comment]
Dupe of https://github.com/APIDevTools/swagger-express-middleware/issues/98
