### ISSUE TITLE
Way to cusomize http401 ?

### ISSUE THREAD

**Issue by walshe** [APIDevTools/swagger-express-middleware#168]
If some one tries to use my swagger ui to hit a secured api, swagger iddleware returns a 401.

This is fine except it causes the browser to display its 'native' basic auth modal dialog which I don't want.  (instead I want them to use the 'Authorize' button in my swagger UI)

..anyway, is there an easy way to tell swagger-middleware to return a 403 instead or some other code ?

**Comment by JamesMessinger** [comment]
@walshe - Swagger Express Middleware just throws errors, which can be handled using standard [Express error-handling middleware](https://expressjs.com/en/guide/error-handling.html).  You can handle the error however you want, including changing the response code and/or customizing the response body.

See the [validation middleware docs](https://apitools.dev/swagger-express-middleware/docs/middleware/validateRequest.html) for more details
