### ISSUE TITLE
FormData fields are undefined since switching to version 4.0.0

### ISSUE THREAD

**Issue by thesharlinator** [APIDevTools/swagger-express-middleware#169]
Hi all
Trying to get some help or insight here. I have just updated my version to 4.0.0. I was previously using 2.0.5, which has a vulnerability. 

Ever since then, any POST formData request is getting stripped of its fields. Has anything changed in the way to declare formData parameters? I checked my YAML and it seems OK, and everything else is working fine (regular POST, put, get etc.)

It's really just the formdata params. 
Here's my YAML for reference

```yaml
  /assets/:
    post:
      tags:
        - asset
      description: create a an asset for a campaign
      operationId: createOne
      consumes:
        - multipart/form-data
      parameters:
        - $ref: '#/definitions/AuthorizationHeader'
        - in: formData
          name: file
          type: string
          format: binary
          description: The file to upload
        - in: formData
          name: campaignId
          type: string
          description: The campaign identifier
      responses:
        "200":
          $ref: '#/definitions/AssetWithId'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
```

And the request body I get:
` [Object: null prototype] {
   file: undefined,
   campaignId: undefined,
 }`

Works like a charm if I revert back to 2.0.5
Am I missing something big? 
PS: I assume this is linked to the multer vulnerability fix? just trying to understand what I need to change to get my formdata back. 
Thanks!

**Comment by JamesMessinger** [comment]
@thesharlinator - Please look at the [Changelog](https://github.com/APIDevTools/swagger-express-middleware/blob/master/CHANGELOG.md), which explains the changes in 4.0.0 and how to adapt to them

**Comment by thesharlinator** [comment]
> @thesharlinator - Please look at the [Changelog](https://github.com/APIDevTools/swagger-express-middleware/blob/master/CHANGELOG.md), which explains the changes in 4.0.0 and how to adapt to them

Thanks for the quick reply! I've been fighting with this for a while now with minimal success, to be honest. 
It looks like my problem is Im using express-fileupload, which seems incompatible with the swagger-express-middleware's parseRequest. 
If I just use the default parseREquest, without specifying multipart options or anything of the sort, do I need to declare any other body parser? 
My YAML is unchanged, so I wonder, do I have to change the YAML as well to OpenAPI 3.0?
