### ISSUE TITLE
Problems when basePath is "/"

### ISSUE THREAD

**Issue by matthiasfeist** [APIDevTools/swagger-express-middleware#17]
Hey there,

In a swagger.json file, I consume with the swagger-express-middleware there is an entry `"basePath": "/"` which causes the endpoints to break. I assume that it appends the / from basePath to other URLs resulting in invalid URLs like `//foobar`.

**Comment by BigstickCarpet** [comment]
If your API is at the root path, then you shouldn't specify a `basePath` at all.  Per the [Swagger 2.0 Spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#patterned-fields):

> The path is appended to the basePath in order to construct the full URL.

So if the `basePath` is `/` and the path is `/foobar`, then the resulting URL will be `//foobar`

**Comment by matthiasfeist** [comment]
hmmm. OK. It doesn't make a lot of sense, though...
The problem is, that you can't always control the swagger.json file you consume...

**Comment by matthiasfeist** [comment]
I still think it would be good, if it would contruct a meaningful URL

**Comment by BigstickCarpet** [comment]
Yeah, that's a good point.  I can see this being something that could easily trip-up a lot of people, so it's worth adding a special-case for it in the code.

**Comment by matthiasfeist** [comment]
I just have no idea where to look for this in the code or otherwise I would have issued a pull request :blush:

**Comment by BigstickCarpet** [comment]
lol.  no worries.  I'm starting a pretty big refactoring this week, so the code is going to shift around a lot anyway.  I'll add this fix while I'm doing that.
