### ISSUE TITLE
validateRequest ignores "format": "uuid" for strings

### ISSUE THREAD

**Issue by RenWenshan** [APIDevTools/swagger-express-middleware#171]
Expecting the following definition to return "400 Bad Request" when an invalid uuid (e.g. "ae926c5a-e28f-4b80-8c00-772eaf7661") is passed in 
```
        "id": {
          "type": "string",
          "format": "uuid"
        }
```

However, `validateRequest()` ignores the format requirement.

Any plan to fix this (or any workaround)?

**Comment by JamesMessinger** [comment]
We currently only support the formats that are specified in [the OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types), which doesn't include "uuid".  But I'd be happy to accept a PR that adds support for it

**Comment by alexandruluca** [comment]
@JamesMessinger Would you consider accepting a PR if I provide one?
