### ISSUE TITLE
what's the difference between @apidevtools/swagger-express-middleware and swagger-express-middleware?

### ISSUE THREAD

**Issue by zacyang** [APIDevTools/swagger-express-middleware#174]
I found its really confusing, on https://www.npmjs.com/package/swagger-express-middleware
there are 2 instruction to install this module, one is
```
npm i swagger-express-middleware
```
the other is in the readme
```
npm install @apidevtools/swagger-express-middleware
```

could you clarify what is the difference? Thanks

**Comment by n1kk** [comment]
I just looked into the `swagger-express-middleware` content and it just reexports `@apidevtools/swagger-express-middleware` package. Doesn't looks like it has anything malicious in it.

`index.js`:
```js
"use strict";
module.exports = require("@apidevtools/swagger-express-middleware");
```

Both packages have [jamesmessinger](https://www.npmjs.com/~jamesmessinger) in contributors, first one also has [rkrauskopf](https://www.npmjs.com/~rkrauskopf) but maybe it's his bot. 
Both packages are same latest version 4.0.2. I assume maybe it's done to be able to use typescript definitions for it? [@types/swagger-express-middleware](https://www.npmjs.com/package/@types/swagger-express-middleware)

**Comment by philsturgeon** [comment]
They're both the same and they're both about to get deprecated unless anyone wants to maintain them.
