### ISSUE TITLE
Support mocking error responses

### ISSUE THREAD

**Issue by winniehell** [APIDevTools/swagger-express-middleware#37]
[Resource](https://github.com/BigstickCarpet/swagger-express-middleware/blob/3f8fc1a/lib/data-store/resource.js#L35) only depends on the [request path](https://github.com/BigstickCarpet/swagger-express-middleware/blob/e46e6a6/lib/mock/query-resource.js#L23) and even though the response is [picked by status code](https://github.com/BigstickCarpet/swagger-express-middleware/blob/3f8fc1a/lib/mock/index.js#L61), the status code is not taken into account when retrieving the response body from data store. This makes it impossible to mock error responses as far as I can see.

There are three ways to change this, in my opinion:
1. add the status code to `Resource` (breaking change)
2. add the status code to `DataStore` (breaking change)
3. introduce an `ErrorResource`/`StatusAwareResource` which can be passed to `DataStore`

Maybe a mix of 1. and 3. is also possible: the status code could be optional part of `Resource`, i.e. not passed to the constructor.

What do you think?

**Comment by winniehell** [comment]
Maybe, I was wrong for the case that the middleware is used with an express application. You can set the data store to be used based on the status code just before it is used to [retrieve the mock data]. This is not really straightforward however.

[retrieve the mock data]: https://github.com/BigstickCarpet/swagger-express-middleware/blob/3f8fc1a/lib/mock/index.js#L120

**Comment by Fabriciu** [comment]
Have you had success mocking error responses?

**Comment by winniehell** [comment]
@Fabriciu No, we decided not to use swagger.
