### ISSUE TITLE
How to use multer with different config for different API endpoints?

### ISSUE THREAD

**Issue by mprokopowicz** [APIDevTools/swagger-express-middleware#46]
I can't figure out how to use multer (from request parser) with different options on different API endpoints.

Let's say we have following API endpoints:
- POST /images
- POST /documents

I need different multer options for this two endpoints, how should i use swagger-express-middleware to apply different multer options?

**Comment by mprokopowicz** [comment]
Clairfied title

**Comment by rkrauskopf** [comment]
Closing this issue due to its age. Please re-open it if the issue is still relevant
