### ISSUE TITLE
How can i pass by mock middleware resources filtering?

### ISSUE THREAD

**Issue by rootatdarkstar** [APIDevTools/swagger-express-middleware#49]
I have some required query params like a `offset` and `limit`. And i doesn't have this fields in my resources, but _filtering apllies to them and i get empty array in response for every request_.
How can I pass by filter? 

```
  swagger:middleware Filtering resources by {"offset":0,"limit":10} +1ms
  swagger:middleware 0 resources matched the filter criteria +4ms
```

I use swagger-express-middleware as part of swagger-server.

**Comment by gregmeldrum** [comment]
+1

I have pagination query params that are not part of the resource so mock is always returning an empty collection. Is there a way around this without writing a custom mock layer? I would be happy if the pagination params were just ignored.
