### ISSUE TITLE
Returning HTTP 404 example error instead error trace

### ISSUE THREAD

**Issue by Fabriciu** [APIDevTools/swagger-express-middleware#60]
Hello guys,

Is there any way to return a 404 error defined in schema instead the error trace?

Thanks!

**Comment by BigstickCarpet** [comment]
Please see the [documentation for the Validate Request Middleware](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/validateRequest.md#validate-request-middleware).  The first code example on that page shows how to use [error handling middleware](http://expressjs.com/en/guide/error-handling.html) to handle errors however you want.

**Comment by baynezy** [comment]
@BigstickCarpet - how would you parse the Swagger definition and build the response to match the spec?

**Comment by stv8** [comment]
I can't seem to get this working either. If I hit a resource that doesn't exist, for example `/pets/9001`, the resource lookup library `ono` appears to handle the error and throws a 404 html page.

**Comment by BigstickCarpet** [comment]
Here's an example app that renders a custom 404 error:  
https://runkit.com/bigstickcarpet/swagger-express-middleware-issue-60

Here's a successful response:
https://swagger-express-middleware-issue-60-vaxoyoikjfqv.runkit.sh/John

Here's the custom 404 response:
https://swagger-express-middleware-issue-60-vaxoyoikjfqv.runkit.sh/Albert

And here's the default Express.JS error page:
https://swagger-express-middleware-issue-60-vaxoyoikjfqv.runkit.sh/fizz/buzz

**Comment by stv8** [comment]
Thanks for the reply. 

I am having no problem triggering a custom error response when a route isn't defined, however I cannot trigger it if a resource 404s. 

For example, if I have a `pets` resource with 10 pets and id's `1-10` via `/pets/:id`, my custom error handler isn't triggered if I try to hit `/pets/11`. 

I believe the `ono` library, which appears to handle resource retrieval, is catching the error before express can hit my custom handler.

**Comment by BigstickCarpet** [comment]
@stv8 - Please look at the example app that I linked to above.  The code does exactly that.  It has a list of names, and it throws a custom 404 error if you specify a name that's not in its list.
