### ISSUE TITLE
Does not convert date-time strings to Date objects if using Swagger composition (allOf)

### ISSUE THREAD

**Issue by JamesMGreene** [APIDevTools/swagger-express-middleware#68]
The Swagger spec supports some concept of composition via keywords like `allOf` (see the section "Composition and Inheritance (Polymorphism)" under [Schema Object](http://swagger.io/specification/#schemaObject)).

However, SEM does not correct handle [at least] converting the input for such definitions into their appropriate data types, at least for strings with a `format: date-time`.

For example, the following schema works with SEM and correctly converts the property "timeStart" into a `Date` object when the body schema is `$ref: '#/definitions/TraceParametersBasic'`:

```yaml
definitions:
  TraceParametersBasic:
    required:
      - timeStart
    properties:
      timeStart:
        type: string
        format: date-time
```

However, if we use schema composition to make a more complex object that consumes that basic schema, **neither** of the properties "timeStart" **nor** "timeEnd" will be converted to `Date` objects when the body schema is `$ref: '#/definitions/TraceParametersEnhanced'`:

```yaml
definitions:
  TraceParametersBasic:
    required:
      - timeStart
    properties:
      timeStart:
        type: string
        format: date-time
  TraceParametersEnhanced:
    allOf:
      - $ref: '#/definitions/TraceParametersBasic'
      - type: object
        required:
          - timeEnd
        properties:
          timeEnd:
            type: string
            format: date-time
```

**Comment by JamesMGreene** [comment]
P.S. I wouldn't be surprised if this affects all data type conversions but `date-time` strings were the one that led me to file this bug and I do not have time to perform more expansive testing right now.

**Comment by mustafar** [comment]
+1
facing the same issue in https://github.com/mustafar/parrot
