### ISSUE TITLE
How I cat disable multipart parsing?

### ISSUE THREAD

**Issue by MaksymRadko** [APIDevTools/swagger-express-middleware#75]
How I cat disable multipart parsing in 
middleware.parseRequest({
      multipart: { // I want disable multipart parsing owerall 
          dest: path.join(__dirname, 'photos')
      }
})

**Comment by BigstickCarpet** [comment]
There's not currently a way to completely disable any of the request parsers, but I think this would be a good thing to add.  Setting any of the parser options to `false` rather than an object should disable that parser.  

For example, to disable multipart parsing:
```javascript
middleware.parseRequest({
    multipart: false,
})
```
