### ISSUE TITLE
why the response include request data

### ISSUE THREAD

**Issue by wstygk** [APIDevTools/swagger-express-middleware#82]
my response data include the  request data ,it's strange, why?

**Comment by BigstickCarpet** [comment]
Please see [the documentation](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#default-behavior) for an explanation of the default behavior of the Mock middleware, and how to customize that behavior

**Comment by rkrauskopf** [comment]
Closing this issue due to its age. Please re-open it if the issue is still relevant
