### ISSUE TITLE
files middleware - Warning when serving spec api json with useBasePath: true

### ISSUE THREAD

**Issue by cdimascio** [APIDevTools/swagger-express-middleware#87]
Files middleware causes warning when serving the swagger json with `useBasePath: true`

The following middleware configuration causes WARNINGS when accessing `<api-root>/api-docs`
```javascript
    app.use(middleware.files({
      // Override the Express App's case-sensitive and strict-routing settings for the Files middleware.
      caseSensitive: false,
      strict: false
    }, {
      useBasePath: true,
      apiPath: /api-docs/,
    }));
```

For example, I see the following when accessing api-docs:
WARNING! Unable to find a Swagger path that matches "/myapi/v1/api-docs"

Adding api-docs to the yaml file works around the warnings, however this is not desired.

**Comment by gonenduk** [comment]
Any updates?

**Comment by gonenduk** [comment]
I checked it. The problem happens when the docs serving URL is under the base path.
For example, if your API base path is /api and your docs path is /api/docs - the warning will be issued.
It does not happen when the docs is served outside the scope of the API.

**Comment by gonenduk** [comment]
You get a warning on the console whenever you try to access a url that does not exist in the YAML or JSON files of your api definitions. You also get a warning when you try to access a path with a verb which is not supported.
You can turn off the warning messages with an environment variable WARN=off
Personally, I don't think they should be logged at all - just return the error (as they do).

**Comment by BebeSparkelSparkel** [comment]
can this be closed?

**Comment by BebeSparkelSparkel** [comment]
2 things

First, I think it should default to sending an error if the path is not found instead of printing to screen. If you do not want it validated there should be a whitelist option.

Second, it seems like there are a lot of open issues with very little activity that go back to 2015 that probably do not matter anymore. These have left me hanging while investigating for solutions. Perhaps after a period of time without any activity there could be a resolution comment and then close the issue.

**Comment by gonenduk** [comment]
The error is sent of course, but a rule of thumb for libraries is never to decide for the main program what to print out on the console. Give the error and let he main program log it or ignore it or whatever it wants to do with it.

Do you have permissions to merge code changes and publish a new version to npm?

**Comment by BebeSparkelSparkel** [comment]
I do not.
