### ISSUE TITLE
JSON Schema validation error when submitting a form with a date field

### ISSUE THREAD

**Issue by vovanmix** [APIDevTools/swagger-express-middleware#89]
Hi! I have a swagger file that looks like this:
```yml
paths:
  /purchases:
    post:
      summary: Submit a purchase
      description: |
        Purchase form
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Booking'
      responses:
        200:
          description: Purchase successful
          schema:
            $ref: '#/definitions/Success'
definitions:
  Booking:
    type: object
    properties:
      tour_id:
        type: integer
        format: int32
      date:
        type: string
        format: date
```
Note the date field that has a format `date`.
When I submit a POST request to `/purchases` with a body that looks like this:
```json
{
      "tour_id": 1,
      "date": "2017-08-11"
}
```
I get this error:
```
JSON Schema validation error. 
Data path: "date" 
Schema path: "/items/properties/date/type" 
Invalid type: object (expected string)
Invalid type: object (expected string)
    at ono (/client/node_modules/ono/lib/index.js:62:17)
    at parseParameter (/client/node_modules/swagger-express-middleware/lib/param-parser.js:148:11)
    at /client/node_modules/swagger-express-middleware/lib/param-parser.js:93:18

Error: JSON Schema validation error. 
Data path: "date" 
Schema path: "/items/properties/date/type" 
Invalid type: object (expected string)
    at ono (/client/node_modules/ono/lib/index.js:62:17)
    at jsonValidate (/client/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:208:11)
    at parseArray (/client/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:435:5)
    at JsonSchema.parse (/client/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:89:14)
    at /client/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:513:42
```

I assume that this library converts the date field to a date object, and passes it to the JSON schema validator, which expects it to be string.

**Comment by BigstickCarpet** [comment]
I'm not able to reproduce the problem.  Maybe I'm doing something different than you.

[Here's my sample code](https://runkit.com/bigstickcarpet/swagger-express-middleware-issue-89)

You can test it yourself by sending a request to
[`https://swagger-express-middleware-issue-89-rb2ucbxv3roy.runkit.sh/`](https://swagger-express-middleware-issue-89-rb2ucbxv3roy.runkit.sh/)

Here's a [cURL](https://curl.haxx.se/) command:

```bash
curl -X POST \
  https://swagger-express-middleware-issue-89-rb2ucbxv3roy.runkit.sh/ \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 607fc1d7-f3d5-096d-a0c9-1b1a1cd84f83' \
  -d '{
	"tour_id": 1,
	"date": "2017-08-11"
}'
```

If you run the above command, you should see this output:

```bash
The request was parsed successfully.

The "tour_id" property is a number with a value of 1
The "date" property is a Date with a value of "2017-08-11T00:00:00.000Z"
```

**Comment by vovanmix** [comment]
Thank you for quick response!
Sorry, my bad, I thought that I simplified the example but I removed the most important part.
Here is the full config and the mock server code that can reproduce the error:
https://runkit.com/vovanmix/swagger-express-middleware-issue-89

I use version 1.0.0-alpha.12

**Comment by BigstickCarpet** [comment]
Ok, thanks for the clarification.  I've [updated my test code](https://runkit.com/bigstickcarpet/swagger-express-middleware-issue-89), and now I'm able to reproduce the bug.  The problem boils down to this:

1. The code successfully validates each object in the array
2. It then converts the date strings to Date objects
3. It then attempts to validate the array, but now the array is invalid because its objects don't match the schema

**Comment by meisterlampe** [comment]
I just ran into the same problem, when using a date-array-query-param.
For example I'm calling the webservice using:
`http://localhost:3000/v1/measurements?createdAfter=2018-03-08T16:30:21.765Z,2018-03-08T16:30:21.765Z`
I get `{code: "INVALID_TYPE", params: Array(2), message: "Expected type string but found type object", …}`

After I debugged, I guess, this is the exact same problem.

The relevant part of the swagger-file is:
```
parameters:
        - name: createdAfter
          in: query
          required: false
          type: array
          items:
            type: string
            format: date-time
```

My other queries, which use only a single date as parameter, are running perfectly fine.

Any hints how to best work around this problem?

Thanks in advance.

**Comment by meisterlampe** [comment]
I just ommited the date-time-format and pass strings. This is working for now. Not nice though.

**Comment by b055man** [comment]
I just faced this problem as well - the schema for the input object I'm dealing with is quite complex and contains multiple array fields, with objects storing date-time fields. Omitting the date-time format for all those fields is not really an option.
@JamesMessinger is there any chance for fixing this issue?
Thanks in advance

**Comment by quiela** [comment]
> I just ommited the date-time-format and pass strings. This is working for now. Not nice though.

Same issue, same not nice solution...

**Comment by mandana-azarpisheh** [comment]
Hi, I
 String american1= sf.getElement(SettingsMenu.AMERICAN_BUTTON).getText();
            sf.assertTrue("Odds format", american1.contains("true"));
 And got error as:
va.lang.AssertionError: Odds format expected [true] but found [false]
How can I fix that to get true?
