### ISSUE TITLE
Responses to POST, PUT, DELETE are not in the format specified in swagger file

### ISSUE THREAD

**Issue by vovanmix** [APIDevTools/swagger-express-middleware#90]
Here's a fragment of my swagger.yml:
```yaml
/purchases:
    post:
      summary: Submit a purchase
      description: |
        Purchase form
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Purchase'
      responses:
        200:
          description: Purchase successful
          schema:
            $ref: '#/definitions/Success'
        422:
          description: Validation error
          schema:
            $ref: '#/definitions/ValidationError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Success:
    type: object
    properties:
      success:
        type: boolean
        enum:
          - true
  Error:
    type: object
    properties:
      success:
        type: boolean
        enum:
          - false
      message:
        type: string
  ValidationError:
    type: object
    properties:
      success:
        type: boolean
        enum:
          - false
      message:
        type: string
      errors:
        type: object
        properties:
          key:
            type: string
        additionalProperties:
          type: string
```
When I submit the correct form, I get a response containing just the form that I submitted:
```json
{
  "bookings": [
    {
      "tour_id": 1,
      "date": "2017-08-11"
    },
    {
      "tour_id": 2,
      "date": "2017-08-12"
    }
  ]
}
```
But the result that I want to get should be like this:
```json
{
  "success": true
}
```
When I get a validation error, I get a HTML response containing the stack trace of the validation error:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Error: The &quot;body&quot; body parameter is invalid ({&quot;bookings&quot;:[{&quot;tour_id&quot;:1,&quot;date&quot;:&quot;2017-08-11&quot;,&quot;time_id&quot;:1,&quot;adults&quot;:1},{&quot;tour_id&quot;:1,&quot;date&quot;:&quot;2017-08-12&quot;,&quot;time_id&quot;:1,&quot;adults&quot;:1,&quot;kids&quot;:0}],&quot;contact_info&quot;:{&quot;email&quot;:&quot;string&quot;,&quot;first_name&quot;:&quot;string&quot;,&quot;last_name&quot;:&quot;string&quot;}}) 
            <br>JSON Schema validation error. 
            <br>Data path: &quot;/bookings/0&quot; 
            <br>Schema path: &quot;/properties/bookings/items/required/4&quot; 
            <br>Missing required property: tour_id
```
What I expect is to get the response that I specified for 422 (or 400), at least empty, but in the correct format (this is an `Example Value` from Swagger online editor):
```json
{
  "success": false,
  "message": "string",
  "errors": {
    "key": "string",
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  }
}
```

Is it doable and is it a desirable feature for this lib? If yes, I can participate in working on it.

**Comment by BigstickCarpet** [comment]
The [default behavior of the Mock middleware](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#default-behavior) is not quite smart enough to determine your desired behavior in this case.  It seems like a pretty reasonable and do-able expectation though, so I'll mark this as an enhancement request.

In the meantime though, you can [customize the default behavior](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#customizing-behavior) to return the result that you expect.  Since you're simply expecting a static "success" response, you can simply add a `default` or `example` response, and the Mock middleware will automatically use it.

**Comment by vovanmix** [comment]
Thanks!
Default responses doesn't seem to work for POST, here's my swagger config and it still returns the resource in response for 200 and html in response to 400:
```
/purchases:
    post:
      summary: Submit a purchase
      description: Purchase form
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Purchase'
      responses:
        200:
          description: If the requested pet doesn't exist, then the Fido will be sent
          schema:
            type: object
            default:
              name: Fido
              type: dog
              dob: 2000-04-16
              tags:
                - furry
                - brown
         400:
          description: If the requested pet doesn't exist, then the Fido will be sent
          schema:
            type: object
            default:
              name: Fido
              type: dog
              dob: 2000-04-16
              tags:
                - furry
                - brown
```

**Comment by BigstickCarpet** [comment]
Oh yeah, that's right.  The `default` and `example` functionality is just for `GET` requests.  But you can still customize the behavior by [modifying the response](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#modifying-the-response) or [skip the Mock middleware altogether](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#skip-the-mock-middleware)

**Comment by vovanmix** [comment]
These options doesn't look like a good fit for the case when you want to set up a mock server quickly based on a swagger file.
At the other hand the example thing will suite it well - you just specify the example and server will just return it when it matches the status code. I will work on a PR to make it work with post requests when I have time.
