### ISSUE TITLE
Validate response body based in swagger schemas

### ISSUE THREAD

**Issue by fantun3s** [APIDevTools/swagger-express-middleware#93]
I think that would be very helpful if swagger-express-middleware, besides Validate Request middleware feature, also had a feature to validate responses.

**Comment by robertmassaioli** [comment]
I think this is the main thing preventing me from using this library. swagger-tools, by default, has support for response validation.

**Comment by igor-savin-ht** [comment]
That would go beyond the scope of middleware, though, as I believe you can't have pre-response middleware in Express, so you'd have to call that validation explicitly.

**Comment by Somebi** [comment]
Bump, indeed, it's strange that this is not implemented. It's very important as well for us.
Why this wasn't implemented?

**Comment by Somebi** [comment]
There is official swagger node module, which does exactly that, but we choose this module, because it's updated more often.
Maybe you can look how that is implemented in their module?

**Comment by Somebi** [comment]
https://github.com/swagger-api/swagger-node
