### ISSUE TITLE
Consider replacing tv4 with ajv

### ISSUE THREAD

**Issue by gunzip** [APIDevTools/swagger-express-middleware#96]
ref. https://www.npmjs.com/package/json-schema-benchmark

https://github.com/epoberezkin/ajv

**Comment by BigstickCarpet** [comment]
I'm currently working on a rewrite of the underlying [JSON Schema library](https://github.com/BigstickCarpet/json-schema-lib) that's used by Swagger-Express-Middleware.  As part of the rewrite, I'm making it possible to plug-in whatever schema validator you want.

**Comment by rkrauskopf** [comment]
Closing this issue due to its age. Please re-open it if the issue is still relevant
