### ISSUE TITLE
Use query parameters to filter the results optionally

### ISSUE THREAD

**Issue by vovanmix** [APIDevTools/swagger-express-middleware#97]
I have `page` & `limit` query params in my swagger file, and my front end code sets them to some values by default. But the mock middleware tries to filter the existing records by `page` and `limit` fields, that are not exist on records. It would be great if we could either make filtering by parameters an option to `middleware.mock`, or add a new property to swagger file to mark fields that should be excluded from filtering.

```yaml
/news:
    get:
      summary: news list
      description: |
        List of all news
      parameters:
        - name: page
          in: query
          description: Results page
          required: false
          type: integer
          format: int32
        - name: limit
          in: query
          description: Number or records to display
          required: false
          type: integer
          format: int32
      responses:
```

**Comment by BigstickCarpet** [comment]
There are a few different ways that you can [customize the behavior of the mock middleware](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#customizing-behavior).  You can inject your own middleware before the mock middleware to modify the request object, or you can completely bypass the default mock behavior and replace it with your own functionality.

**Comment by TimoKorinth** [comment]
I think there was a pull request to add filter and offset params to the collection query (#78). Can't we just accept it or modify it to support this highly requested feature? I would really love to support, because that is a critical feature for me.
