### ISSUE TITLE
old version of multer is a security risk

### ISSUE THREAD

**Issue by tsukhu** [APIDevTools/swagger-express-middleware#98]
As per the code it mentions we are using an old version of multer due to an old bug https://github.com/expressjs/multer/issues/212. This has now been fixed in the never versions of multer.

The old version of multer is reported as a security risk https://snyk.io/test/github/BigstickCarpet/swagger-express-middleware 
![middleware_vunerability](https://user-images.githubusercontent.com/846306/30902257-3ab5e2b8-a388-11e7-9d43-668824ecd8c0.png)

**Comment by tsukhu** [comment]
I tried to fix this issue , but have not submitted it as a PR as I get this error

![image](https://user-images.githubusercontent.com/846306/30912159-24e820ce-a3a9-11e7-8980-6400b9c34e5c.png)

What am I missing here ..

Here are the changes done
https://github.com/tks-PRs/swagger-express-middleware/commit/40814c1c52729266fe5e0dddc8db8f9e5e40c7d5

**Comment by tsukhu** [comment]
It would be great if someone can look into this issue..

**Comment by tsukhu** [comment]
Hi @BigstickCarpet it will be great if you could update the versions causing the vunerability and related a new update.

**Comment by benjamine** [comment]
came for the same issue, I saw this comment:
https://github.com/APIDevTools/swagger-express-middleware/blob/master/lib/request-parser.js#L36

and noticed that multer already fixed the issue mentioned, so in theory it should be possible to uncomment that block and start using multer 1.x

**Comment by JamesMessinger** [comment]
We've upgraded to the latest version of Multer in [the v3 branch](https://github.com/APIDevTools/swagger-express-middleware/tree/v3), which we're working hard to get released as soon as possible.

**Comment by RenWenshan** [comment]
@JamesMessinger thanks for the update. Any chance to upgrade multer in v2 as well? If not what's the approximate release date for v3?

**Comment by dave-irvine** [comment]
This has come up again with a new qs vulnerability. https://www.npmjs.com/advisories/1469. I appreciate that the multer upgrade is complete in the v3 branch, but even in the future once that branch is released I'd expect people with Swagger v2 definitions will continue to need to use the v2 branch of this middleware? In such a case there is a definite need for the multer upgrade in the v2 branch. Any thoughts @JamesMessinger ?

**Comment by JamesMessinger** [comment]
Unfortunately, upgrading multer in the 2.0 branch is not possible (or at least very difficult) due to breaking changes in key functionality that Swagger Express Middleware relies on.

See [this issue](https://github.com/APIDevTools/swagger-express-middleware/issues/158) for the plans for the 3.0 branch

**Comment by JamesMessinger** [comment]
This issue has now been fixed by PR #165.  HUGE THANKS to @jphenow for the PR 🏆
